// The MIT License (MIT)
//
// Copyright (c) 2015-2016 Qvik (www.qvik.fi)
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

import Foundation

/**
 A generic keychain wrapper utility. For information on the keychain, see:
 `https://developer.apple.com/library/content/documentation/Security/Conceptual/keychainServConcepts/02concepts/concepts.html`
 */
public class Keychain {
    private let serviceName: String
    private let accessMode: String
    private var accessGroup: String?

    /// Errors generated by the methods in this class.
    public enum Errors: Error {
        case apiCallFailed(statusCode: OSStatus)
    }

    /**
     Constructs the wrapper. 
     
     - parameter serviceName: Name for your 'service' using the keychain; eg. com.company.MyApp
     - parameter accessMode: One of:
       - `kSecAttrAccessibleWhenUnlocked`
       - `kSecAttrAccessibleAfterFirstUnlock`
       - `kSecAttrAccessibleAlways`
       - `kSecAttrAccessibleWhenPasscodeSetThisDeviceOnly`
       - `kSecAttrAccessibleWhenUnlockedThisDeviceOnly`
       - `kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly`
       - `kSecAttrAccessibleAlwaysThisDeviceOnly`
     - parameter accessGroup: Name for an access group. Access groups can be used to share keychain items among two or more applications. Optional.
     */
    public init(serviceName: String, accessMode: String, accessGroup: String? = nil) {
        self.serviceName = serviceName
        self.accessMode = accessMode
        self.accessGroup = accessGroup
    }

    /**
     Creates the common attribute array used in all the access methods.
     
     - returns: The attribute array for accessing underlying keychain
     */
    private func createAttributes() -> [String: String] {
        var attributes = [
            kSecClass as String: (kSecClassGenericPassword as String),
            kSecAttrService as String: self.serviceName
        ]

        if let accessGroup = self.accessGroup {
            attributes[kSecAttrAccessGroup as String] = accessGroup
        }

        return attributes
    }

    /**
     Adds a new key to the keychain. 
     
     - parameter key: a string key
     - parameter value: a string value
     - throws: Errors.apiCallFailed if the API call fails
     */
    public func add(key: String, value: String) throws {
        var attributes = createAttributes()
        attributes[kSecAttrAccount as String] = key
        attributes[kSecValueData as String] = value

        let status = SecItemAdd(attributes as CFDictionary, nil)

        if status != errSecSuccess {
            throw Errors.apiCallFailed(statusCode: status)
        }
    }
}
